version: "3.7"

services:
  mongo:
    image: mongo:6
    volumes:
      - data:/data/db

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3042:3000"
    environment:
      JWT_SECRET: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6InRvbWFzaGNvIiwiZXhwIjoxNjk0MzUxODEyLCJpYXQiOjE2OTQzNTE4MTJ9.5zm5h8roLN1uHvpfW59Mvs2ma5xaKTt5O_JKR3wovZg
      MONGO_URL: mongodb://mongo:27017/todo

volumes:
  data:
